sudo: required

before_install:
   - sudo apt-get update
   - sudo apt-get install postgresql-9.5
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3

install: "true"
language: erlang
otp_release:
  - 18.2.1
  - 17.5
script:
  - ./rebar3 do xref,ct,dialyzer,coveralls send
